version: "3"
services:
  api:
    image: "docker.io/s1solucoes/fastapi-skel:latest"
    build:
      context: "."
      target: "production"
    env_file:
      - "local.env"
      - "docker.env"
    ports:
      - mode: "host"
        target: 8000
        published: 8001
